/*** Eclipse Class Decompiler plugin, copyright (c) 2016 Chen Chao (cnfree2000@hotmail.com) ***/
package com.gewara.ucenter.constant;

import java.util.Arrays;
import java.util.List;

public class MemberConstant {
	public static final String REGISTER_EMAIL = "email";
	public static final String REGISTER_MOBLIE = "mobile";
	public static final String REGISTER_CODE = "code";
	public static final String REGISTER_APP = "app";
	public static final String NEWTASK = "newtask";
	public static final String TASK_CONFIRMREG = "confirmreg";
	public static final String TASK_SENDWALA = "sendwala";
	public static final String TASK_UPDATE_HEAD_PIC = "headpic";
	public static final String TASK_BINDMOBILE = "bindmobile";
	public static final String TASK_BUYED_TICKET = "buyticket";
	public static final String MODIFY_NICKNAME = "modify_nickname";
	public static final List<String> TASK_LIST = Arrays
			.asList(new String[] { "headpic", "buyticket", "bindmobile", "confirmreg", "sendwala" });
	public static final String TAG_SOURCE = "bindstatus";
	public static final String TAG_MOBILE_BINDTIME = "mblbindtime";
	public static final String TAG_EMAIL_BINDTIME = "emlbindtime";
	public static final String TAG_DANGER = "danger";
	public static final String SOURCE_ALIPAY = "alipay";
	public static final String SOURCE_SDO = "sdo";
	public static final String SOURCE_SINA = "sina";
	public static final String SOURCE_QQ = "qq";
	public static final String SOURCE_TENCENT = "tencent";
	public static final String SOURCE_CHINAPAY = "chinapay";
	public static final String SOURCE_DYNCODE = "dyncode";
	public static final String SOURCE_TAOBAO = "taobao";
	public static final String SOURCE_BAIDU = "baidu";
	public static final String SOURCE_FILMFEST = "filmfest";
	public static final String SOURCE_WEIXIN = "weixin";
	public static final String SOURCE_WEIXIN_DELETE = "weixin_delete";
	public static final String SOURCE_PINGANFU = "pinganfu";
	public static final String SOURCE_CMBCQM = "cmbcqm";
	public static final String SOURCE_BANKCOMM = "bankcomm";
	public static final String SOURCE_CHUBAO = "chubao";
	public static final String SHORT_ALIPAY = "a";
	public static final String SHORT_SINA = "S";
	public static final String SHORT_QQ = "q";
	public static final String SHORT_TENCENT = "t";
	public static final String SHORT_CHINAPAY = "c";
	public static final String SHORT_FILMFEST = "f";
	public static final String CATEGORY_ALIKUAIJIE = "alikuaijie";
	public static final String CATEGORY_ALIWALLET = "aliwallet";
	public static final String ACTION_REGCARD = "regcard";
	public static final String ACTION_MODPWD = "modpwd";
	public static final String ACTION_NEWTASK = "newtask";
	public static final String ACTION_SETPAYPWD = "setpaypwd";
	public static final String ACTION_GETPAYPWD = "getpaypwd";
	public static final String ACTION_MDYPAYPWD = "mdypaypwd";
	public static final String ACTION_MODEMAIL = "modemail";
	public static final String ACTION_BINDMOBILE = "bindmobile";
	public static final String ACTION_VDDRAWMOBILE = "validdrawmobile";
	public static final String ACTION_CHGBINDMOBILE = "chgbindmobile";
	public static final String ACTION_RELIEVEMOBILE = "relievemobile";
	public static final String ACTION_TOWABI = "towabi";
	public static final String ACTION_DROPMESS = "drpmessage";
	public static final String ACTION_LOGIN = "login";
	public static final String OM_MOBILE = "mobile";
	public static final String OPENMEMBER = "openMember";
	public static final String ALIWALLET_SHORTTOKEN = "aliwallet_shorttoken";
	public static final String ALIWALLET_LONGTOKEN = "aliwallet_longtoken";
	public static final String ALIWALLET_EXPIRESIN = "aliwallet_expiresIn";
	public static final String ALIWALLET_REEXPIRESIN = "aliwallet_reExpiresIn";
	public static final String ALIWALLET_SHORTVALIDTIME = "aliwallet_shortvalidtime";
	public static final String ALIWALLET_LONGVALIDTIME = "aliwallet_longvalidtime";
	public static final String ALIWALLET_EXTERN_TOKEN = "extern_token";
	public static final String PINGAN1QBPAY_LOGINKEND = "loginToken";
	public static final String PINGAN1QBPAY_REFRESHTOKEN = "refreshToken";
	public static final String BINDMOBILE_STATUS_Y = "Y";
	public static final String BINDMOBILE_STATUS_N = "N";
	public static final String BINDMOBILE_STATUS_YS = "Y_S";
	public static final String TYPE_MEMBER_BAND = "member_band_type";
	public static final String TYPE_MEMBER_BAND_AND_GET_HEAD_PIC = "member_band_type_and_get_head_pic";
	public static final String NEEDVALID_Y = "Y";
	public static final String NEEDVALID_N = "N";
	public static final String NEEDVALID_U = "U";
	public static final String NEEDVALID_MSG = "为保证您的账号安全，请按短信指示验证账号，完成验证后请重试！";
	public static final String RESET_PASSWORD = "mustResetPass";
	public static final String RESET_PASS_ERROR_MSG = "您的账户存在安全风险，请点击“忘记密码”重设密码！";
	public static final String RELOGIN_MSG = "获取登录信息失败，请刷新重试或重新登录！";
}