/*** Eclipse Class Decompiler plugin, copyright (c) 2016 Chen Chao (cnfree2000@hotmail.com) ***/
package com.gewara.cons;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import org.apache.commons.collections.map.UnmodifiableMap;

public class RefundConstant {
	public static final String STATUS_APPLY = "apply";
	public static final String STATUS_ACCEPT = "accept";
	public static final String STATUS_REJECT = "reject";
	public static final String STATUS_SUCCESS = "success";
	public static final String STATUS_FINISHED = "finish";
	public static final String STATUS_USER_APPLY = "user_apply";
	public static final String STATUS_USER_REJECT = "user_reject";
	public static final String OP_CANCEL_TICKET = "cancelTicket";
	public static final String OP_ADJUST_SETTLE = "adjustSettle";
	public static final String OP_COMPENSATE = "compensate";
	public static final String OP_RET2PARTNER = "ret2Partner";
	public static final String OP_LOCK_TICKET = "lockTicket";
	public static final String OP_RESULT_CANCEL_SUCCESS = "cancelSuccess";
	public static final String OP_RESULT_CANCEL_FAILURE = "cancelFailure";
	public static final String REFUNDTYPE_FULL = "full";
	public static final String REFUNDTYPE_PART = "part";
	public static final String REFUNDTYPE_SUPPLEMENT = "supplement";
	public static final String REFUNDTYPE_GEWARA = "gewara";
	public static final String LOCK_SUCCESS = "lock_success";
	public static final String LOCK_TAKE = "lock_take";
	public static final String LOCK_FAILURE = "lock_failure";
	public static final String UN_LOCK_Y = "Y";
	public static final String UN_LOCK_N = "N";
	public static final String REASON_UNKNOWN = "unknown";
	public static final String REASON_USER = "user";
	public static final String REASON_GEWA = "gewa";
	public static final String REASON_GEWA_SYS = "gewa_sys";
	public static final String REASON_MERCHANT = "merchant";
	public static final String REASON_MERCHANT_OPI = "merchant_opi";
	public static final String REASON_PRICE = "price";
	public static final String REASON_CANCELTICKET = "cancelTicket";
	public static final String REASON_BAOCHANG = "baochang_fail";
	public static final int COUNT_MONTH_MEMBER = 3;
	public static final int COUNT_WEEK_MEMBER = 2;
	public static final int COUNT_MONTH_CINEMA = 400;
	public static final int COUNT_DAY_CINEMA = 30;
	public static final String RETBACK_Y = "Y";
	public static final String RETBACK_N = "N";
	public static final String RETBACK_OTHER = "O";
	public static final String RETBACK_SUBMIT = "S";
	public static final String RETBACK_REFUND = "R";
	public static final String RETBACK_FAILURE = "F";
	public static final String REFUND_MANAGE_DEAL = "manageDeal";
	public static final String REFUND_FINANCE_DEAL = "financeDeal";
	public static final String REFUND_FINANCE_STATUS = "status";
	public static final String REFUND_FINANCE_RESON = "reson";
	public static final String TR_NORMAL_REFUND = "Y_NORMAL_R";
	public static final String TR_MERCHANT_REFUND = "Y_MERCHANT_R";
	public static final String TR_MERCHANT_NO = "Y_MERCHANT_N";
	public static final String TR_SETTLE_MERCHANT_NO = "S_MERCHANT_N";
	public static final String TR_SETTLE_GEWA_REFUND = "S_GEWA_R";
	public static final String ORIGIN_USER = "USER";
	public static final String ORIGIN_KF = "KF";
	public static final String CLIENTTYPE_PC = "pc";
	public static final String CLIENTTYPE_WAP = "wap";
	public static final String CLIENTTYPE_APP = "app";
	public static final String ClIENTTYPE_API = "api";
	public static final String REFUND_API_METHOD_ALISCANPAY = "aliScanPay";
	public static final String REFUND_API_METHOD_ALISMARTMOBILEPAY = "aliSmartMobilePay";
	public static final String REFUND_API_METHOD_ALIWAPPAY = "aliwapPay";
	public static final String REFUND_API_METHOD_DIRECTPAY = "directPay";
	public static final String ABC_OTHERINFO_AMOUNT = "amount";
	public static final String ABC_OTHERINFO_POINT = "point";
	public static final Map<String, String> textMap;
	public static final Map<String, String> refundTypeMap;
	public static final Map<String, String> reasonTypeMap;
	public static final Map<String, String> supplementReasonMap;
	public static final Map<String, String> retbackMap;
	public static final Map<String, String> ticketRefundTextMap;
	public static final Map<String, String> refundApiPayMethodMap;

	static {
		HashMap tmp = new HashMap();
		tmp.put("apply", "新申请");
		tmp.put("reject", "不接收退款");
		tmp.put("success", "退款成功");
		textMap = UnmodifiableMap.decorate(tmp);
		HashMap tmpRefund = new HashMap();
		tmpRefund.put("full", "全额退款");
		tmpRefund.put("part", "部分退款");
		tmpRefund.put("supplement", "调价退款");
		tmpRefund.put("gewara", "格瓦拉退款");
		refundTypeMap = UnmodifiableMap.decorate(tmpRefund);
		LinkedHashMap tmpReason = new LinkedHashMap();
		tmpReason.put("cancelTicket", "可退票场馆正常退票");
		tmpReason.put("user", "用户原因要求退款");
		tmpReason.put("merchant", "场馆放映中故障退票");
		tmpReason.put("merchant_opi", "场馆通知场次更改或取票退票");
		tmpReason.put("price", "场馆通知价格调整");
		tmpReason.put("gewa", "Gewa场次设置错误");
		tmpReason.put("gewa_sys", "Gewa系统错误");
		tmpReason.put("baochang_fail", "包场失败退款");
		tmpReason.put("unknown", "其它原因");
		reasonTypeMap = UnmodifiableMap.decorate(tmpReason);
		LinkedHashMap tmpSupplementMap = new LinkedHashMap();
		tmpSupplementMap.put("price", "场馆通知价格调整");
		tmpSupplementMap.put("gewa", "Gewa场次设置错误");
		supplementReasonMap = UnmodifiableMap.decorate(tmpSupplementMap);
		LinkedHashMap tmpRetack = new LinkedHashMap();
		tmpRetack.put("Y", "需要");
		tmpRetack.put("N", "不需要");
		tmpRetack.put("O", "参见描述");
		tmpRetack.put("S", "已提交财务");
		tmpRetack.put("R", "财务成功");
		tmpRetack.put("F", "财务失败");
		retbackMap = UnmodifiableMap.decorate(tmpRetack);
		LinkedHashMap settleTmpMap = new LinkedHashMap();
		settleTmpMap.put("Y_NORMAL_R", "正常退票不结算");
		settleTmpMap.put("Y_MERCHANT_R", "影院已退票不结算");
		settleTmpMap.put("Y_MERCHANT_N", "影院未退票不结算");
		settleTmpMap.put("S_MERCHANT_N", "影院未退票需结算");
		settleTmpMap.put("S_GEWA_R", "格瓦拉单方退票");
		ticketRefundTextMap = UnmodifiableMap.decorate(settleTmpMap);
		HashMap payMethodMap = new HashMap();
		payMethodMap.put("aliScanPay", "支付宝扫码支付");
		payMethodMap.put("aliSmartMobilePay", "支付宝手机端-安全支付");
		payMethodMap.put("aliwapPay", "支付宝手机端-WAP支付");
		payMethodMap.put("directPay", "支付宝PC端");
		refundApiPayMethodMap = UnmodifiableMap.decorate(payMethodMap);
	}
}